In [1]:
!pip install scikit-multilearn

     |████████████████████████████████| 89 kB 423 kB/s             
You should consider upgrading via the '/home/qlinhta/PycharmProjects/Multi-label-classification/venv/bin/python -m pip install --upgrade pip' command.


In [44]:
import numpy as np
from sklearn.datasets import make_multilabel_classification
from sklearn.model_selection import train_test_split
from skmultilearn.problem_transform import BinaryRelevance
from sklearn.metrics import accuracy_score
from skmultilearn.problem_transform import ClassifierChain
from sklearn.naive_bayes import GaussianNB
from skmultilearn.problem_transform import LabelPowerset
from skmultilearn.adapt import MLkNN
from numpy import mean
from numpy import std
from sklearn.datasets import make_multilabel_classification
from sklearn.model_selection import RepeatedKFold
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
import numpy as np
import tensorflow

2022-04-25 22:37:12.158309: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-04-25 22:37:12.158360: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


In [31]:
X, y = make_multilabel_classification(n_samples = 100, n_features = 20, n_classes = 5, sparse=False, n_labels=2, return_indicator="dense", allow_unlabeled= False)
X, y

(array([[1., 3., 1., ..., 4., 1., 2.],
        [5., 1., 4., ..., 7., 6., 4.],
        [2., 5., 2., ..., 3., 0., 5.],
        ...,
        [2., 1., 2., ..., 6., 4., 3.],
        [2., 1., 0., ..., 5., 1., 3.],
        [3., 1., 2., ..., 3., 2., 2.]]),
 array([[0, 1, 0, 0, 1],
        [1, 1, 1, 0, 0],
        [0, 1, 0, 0, 1],
        [0, 1, 1, 0, 1],
        [0, 1, 0, 0, 0],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 0],
        [1, 1, 0, 0, 0],
        [1, 1, 0, 0, 1],
        [0, 1, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [0, 0, 0, 0, 1],
        [1, 0, 0, 0, 0],
        [0, 0, 0, 0, 1],
        [0, 1, 0, 1, 1],
        [1, 1, 0, 0, 0],
        [1, 1, 1, 0, 0],
        [0, 1, 1, 0, 1],
        [1, 0, 0, 0, 1],
        [0, 0, 0, 0, 1],
        [0, 1, 0, 0, 1],
        [1, 1, 1, 0, 1],
        [1, 0, 0, 0, 0],
        [1, 1, 0, 0, 1],
        [1, 0, 1, 0, 0],
        [1, 1, 1, 1, 1],
        [0, 0, 0, 1, 0],
        [0, 1, 1, 0, 0],
        [1, 1, 0, 0, 1],
        [0, 1, 0, 0, 1],
 

In [32]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, test_size=0.2)

In [33]:
br_clf = BinaryRelevance(GaussianNB())
br_clf.fit(X_train, y_train)
y_pred = br_clf.predict(X_test)

In [34]:
def hamming_score(y_true, y_pred, normalize=True, sample_weight=None):
    acc_list = []
    for i in range(y_true.shape[0]):
        set_true = set(np.where(y_true[i])[0])
        set_pred = set(np.where(y_pred[i])[0])
        tmp_a = None
        if len(set_true) == 0 and len(set_pred) == 0:
            tmp_a = 1
        else:
            tmp_a = len(set_true.intersection(set_pred)) / float(len(set_true.union(set_pred)))
        acc_list.append(tmp_a)
    return np.mean(acc_list)

In [35]:
print(accuracy_score(y_pred.todense(), y_test))
print(hamming_score(np.array(y_pred.todense()), y_test))

0.45
0.725


In [36]:
y_pred.todense(), y_test

(matrix([[0, 1, 0, 0, 1],
         [0, 1, 0, 0, 0],
         [0, 0, 0, 0, 1],
         [1, 0, 0, 0, 1],
         [1, 0, 0, 0, 1],
         [0, 0, 0, 0, 1],
         [1, 0, 1, 0, 0],
         [0, 1, 0, 0, 0],
         [1, 1, 0, 0, 1],
         [0, 1, 0, 0, 1],
         [1, 1, 0, 0, 1],
         [0, 1, 0, 1, 0],
         [0, 1, 0, 0, 1],
         [0, 1, 0, 0, 1],
         [1, 1, 1, 0, 1],
         [0, 1, 0, 0, 0],
         [0, 1, 0, 0, 0],
         [0, 1, 0, 0, 0],
         [1, 0, 0, 0, 0],
         [1, 0, 0, 0, 0]]),
 array([[0, 0, 0, 0, 1],
        [0, 1, 0, 0, 0],
        [0, 0, 0, 1, 1],
        [1, 0, 1, 0, 1],
        [0, 0, 0, 0, 1],
        [0, 0, 0, 0, 1],
        [1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [1, 0, 0, 0, 1],
        [0, 1, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [0, 1, 0, 1, 0],
        [1, 1, 1, 0, 1],
        [0, 1, 0, 0, 0],
        [1, 1, 1, 0, 1],
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 1, 0, 0, 0],
        [1, 0, 0, 0, 0],
   

In [37]:
cc_clf = ClassifierChain(GaussianNB())
cc_clf.fit(X_train, y_train)
y_pred = cc_clf.predict(X_test)

In [38]:
print(accuracy_score(y_pred.todense(), y_test))
print(hamming_score(np.array(y_pred.todense()), y_test))

0.35
0.675


In [39]:
lp_clf = LabelPowerset(GaussianNB())
lp_clf.fit(X_train, y_train)
y_pred = lp_clf.predict(X_test)

In [40]:
print(accuracy_score(y_pred.todense(), y_test))
print(hamming_score(np.array(y_pred.todense()), y_test))

0.25
0.55


In [41]:
mlknn_clf = MLkNN(k=5)
mlknn_clf.fit(X_train, y_train)
y_pred = mlknn_clf.predict(X_test)

TypeError: __init__() takes 1 positional argument but 2 were given

In [42]:
print(accuracy_score(y_pred.todense(), y_test))
print(hamming_score(np.array(y_pred.todense()), y_test))

0.25
0.55


In [45]:
model = Sequential()
model.add(Dense(32, input_dim = X.shape[1], activation="relu"))
model.add(Dense(y.shape[1], activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer = "adam", metrics=['accuracy', 'binary_accuracy'])

2022-04-25 22:37:20.586702: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2022-04-25 22:37:20.586751: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2022-04-25 22:37:20.586777: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (cessna): /proc/driver/nvidia/version does not exist
2022-04-25 22:37:20.587116: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [46]:
model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=50, batch_size=16)

Epoch 1/50
5/5 [==============================] - 1s 76ms/step - loss: 0.7785 - accuracy: 0.1375 - binary_accuracy: 0.6125 - val_loss: 0.7695 - val_accuracy: 0.2000 - val_binary_accuracy: 0.6000
Epoch 2/50
5/5 [==============================] - 0s 11ms/step - loss: 0.7297 - accuracy: 0.2625 - binary_accuracy: 0.6250 - val_loss: 0.7535 - val_accuracy: 0.2500 - val_binary_accuracy: 0.6000
Epoch 3/50
5/5 [==============================] - 0s 12ms/step - loss: 0.7016 - accuracy: 0.3000 - binary_accuracy: 0.6225 - val_loss: 0.7367 - val_accuracy: 0.3000 - val_binary_accuracy: 0.5800
Epoch 4/50
5/5 [==============================] - 0s 10ms/step - loss: 0.6779 - accuracy: 0.3375 - binary_accuracy: 0.6325 - val_loss: 0.7123 - val_accuracy: 0.3500 - val_binary_accuracy: 0.5800
Epoch 5/50
5/5 [==============================] - 0s 10ms/step - loss: 0.6534 - accuracy: 0.3875 - binary_accuracy: 0.6475 - val_loss: 0.6935 - val_accuracy: 0.3500 - val_binary_accuracy: 0.6100
Epoch 6/50
5/5 [=========

In [47]:
X_train.shape

(80, 20)